env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules: 
  react/prop-types: off
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/naming-convention':
    - error
    - 
      selector: function
      format: 
        - camelCase
        - PascalCase
    - 
      selector: parameter
      format:
        - camelCase
      leadingUnderscore: allow
    - 
      selector: interface
      format: 
        - PascalCase
      custom:
        regex: ^I[A-Z]
        match: true
  prettier/prettier:
    - error
settings:
  react:
    version: detect